### ISSUE TITLE
When are Notifications going to be RELIABLE??? (Android + all other Element platform releases

### ISSUE THREAD

**Issue by BloodyIron** [element-hq/element-android#8815]
### Steps to reproduce

Notifications have been extremely unreliable for going on 5 years now, and there are an endless supply of github issues for the Android, Desktop, Web, iOS, other platforms.

It's gotten to the point now where I really don't see ANY developer engagement on this topic, or even any actual interest in having it corrected.

It is completely pointless to use any chat program where notifications of messages (or even having the messages at all) are as unreliable (extremely unreliable) as they are with the Element + Matrix ecosystem.

I don't want to switch away from Element  + Matrix, but frankly this is now being ignored by the developers (so far as I can tell) and it's genuinely that big of a deal that if this really isn't taken seriously, myself and many others are going to just stop using Element. I know many already have.

The devs NEEEEEEED to take this seriously. This is a CHAT app. It's extremely obvious why this matters, and why the notifications (and background sync/related) problems NEED TO BE COMPREHENSIVELY FIXED ON ALL PLATFORMS.

This issue is not tied to any specific version or platform, it happens on ALL of them and has done so for years.

Many people have already submitted logs, reports, and on and on and on... only to lead to silence from the devs, and no releases with any changes improving it.

So... WHEN is this going to be taken SERIOUSLY???

### Outcome

.

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by sans-c** [comment]
I'd like to second this. I just came here to see if there are any new bug reports regarding notifications because they have been extremely unreliable for me since a few weeks now.

Element's notifications on Android have always been a little bit finicky in my experience but it has gotten to a point where I do not get notifications at all for hours on end. Only when I explicitely open the app, I notice that I missed messages from ages ago.

The built-in notifications trouble shooter says that everything is fine, but it definitely is not. For me the issue is most prevalent with a ntfy-setup. Background sync does work more or less but even there I get delays which cannot be explained by my settings.

I also know people who have all sorts of notification issues and who consider turning away from Element/Matrix which is a shame really. In spirit of the original post: yes, notifications should be a chief concern for a chat app.

I am willing to provide logs/more info/whatever is needed but it seems there is alreay a huge amount of data available from previous bug reports.

**Comment by BloodyIron** [comment]
I would like to bring attention that the issues I myself have observed (me and those around me using Element/Matrix) see the issues not just for android, but desktop too, so it looks to be an ecosystem-wide problem. Problems that have been present for years, getting fixed, breaking again, fixed, breaking again... And now seemingly radio silence from the devs on a critical aspect to _any_ chat ecosystem.

**Comment by akallabeth** [comment]
got an incident yesterday where my android phone did not get notifications (not even synced when opening the rooms) while the laptop in the same network got updates.
took a day to get fixed (account on matrix.org and https://status.matrix.org/ did not show degradation of service)

so, the notifications are getting more reliable for me, but the service does have hickups more often these days it seems

**Comment by BloodyIron** [comment]
Can we PLEASE get notifications fixed in the Element ecosystem already? It's been going on like **4 YEARS** where this has been a problem.

**Comment by iamtalhaasghar** [comment]
> The "Mark as Read" feature in the Pop-up notifications is not working for my Android phone. Needs to be fixed please

looks like you are facing this issue https://github.com/element-hq/element-android/issues/3394. May be kindly provide some context & video if possible.

**Comment by stephen304** [comment]
@iamtalhaasghar There are already several videos in that issue, one of which is mine. I still experience the issue and it's unclear what more info is needed for a fix to be prioritized.

**Comment by iamtalhaasghar** [comment]
> This repo and this version of the element app is in maintenance mode. We are only fixing security issues and high priority bugs.
> We currently have (or going to have) the 2 apps in the store: Element and Element X. When ready, the Element app will use the Element X code. Element X is a temporary app using a code name.
> 

src: https://github.com/element-hq/element-android/issues/8606#issuecomment-1669902114

@stephen304

**Comment by stephen304** [comment]
@iamtalhaasghar Right, that's another good reason why adding more copies of issue reproduction videos is kind of a fruitless effort.

**Comment by warioishere** [comment]
I am also having issues with notifications. I am calling for help and finding infos for years. Using own ntfy server, Messages notifications work, but somestimes with a huge delay, at least they work,  but calling notification doesnt work at all. Switching to google servers changes this behavior instantly. Faster notification and also call notification works.

I am really sad, just looked a bit through and seems that a lot of people are having this issue.

**Comment by BloodyIron** [comment]
> I am also having issues with notifications. I am calling for help and finding infos for years. Using own ntfy server, Messages notifications work, but somestimes with a huge delay, at least they work, but calling notification doesnt work at all. Switching to google servers changes this behavior instantly. Faster notification and also call notification works.
> 
> I am really sad, just looked a bit through and seems that a lot of people are having this issue.

What do you mean by switching to google servers? I don't exactly follow you on how that lines-up with Element. Which google servers for which services?

**Comment by warioishere** [comment]
> > I am also having issues with notifications. I am calling for help and finding infos for years. Using own ntfy server, Messages notifications work, but somestimes with a huge delay, at least they work, but calling notification doesnt work at all. Switching to google servers changes this behavior instantly. Faster notification and also call notification works.
> > I am really sad, just looked a bit through and seems that a lot of people are having this issue.
> 
> What do you mean by switching to google servers? I don't exactly follow you on how that lines-up with Element. Which google servers for which services?

should be hard to understand. I mean switching to google Push (FCM) 
I dont think there much other options and you should understand pretty well, what I mean with Google Push Servers Works on Element, Ntfy doesnt work or very unreliable.

I think it should be first priority for a secure and private messenger like element to support ntfy push implemention. 
I really dont know if the cause is synapse itself or element.

the issues are multiple present. All of them dont realy get answered at all, here are my two issues:

https://github.com/element-hq/synapse/issues/17269
https://github.com/element-hq/element-android/issues/8761

**Comment by BloodyIron** [comment]
> > > I am also having issues with notifications. I am calling for help and finding infos for years. Using own ntfy server, Messages notifications work, but somestimes with a huge delay, at least they work, but calling notification doesnt work at all. Switching to google servers changes this behavior instantly. Faster notification and also call notification works.
> > > I am really sad, just looked a bit through and seems that a lot of people are having this issue.
> > 
> > 
> > What do you mean by switching to google servers? I don't exactly follow you on how that lines-up with Element. Which google servers for which services?
> 
> shouldnt be so hard to understand? I mean switching to google Push (FCM) I dont think there much other options and you should understand pretty well, what I mean with Google Push Servers Works on Element, Ntfy doesnt work or very unreliable.
> 
> I think it should be first priority for a secure and private messenger like element to support ntfy push implemention. I really dont know if the cause is synapse itself or element.
> 
> the issues are multiple present. All of them dont realy get answered at all, here are my two issues:
> 
> [element-hq/synapse#17269](https://github.com/element-hq/synapse/issues/17269) #8761


Google Push isn't a server, it's a service local to your device, which is where the confusion comes from.

In my case I/we have already been using Google Push Services for actual years and still have problems.

And yeah it is unclear if it's a synapse/matrix issue or Element issue, but the silence from github issue lack-of-engagement is deafening. They (Element Devs) used to actually work on notification problems but stopped I think well over a year ago. I have no idea why.

**Comment by warioishere** [comment]
> > > > I am also having issues with notifications. I am calling for help and finding infos for years. Using own ntfy server, Messages notifications work, but somestimes with a huge delay, at least they work, but calling notification doesnt work at all. Switching to google servers changes this behavior instantly. Faster notification and also call notification works.
> > > > I am really sad, just looked a bit through and seems that a lot of people are having this issue.
> > > 
> > > 
> > > What do you mean by switching to google servers? I don't exactly follow you on how that lines-up with Element. Which google servers for which services?
> > 
> > 
> > shouldnt be so hard to understand? I mean switching to google Push (FCM) I dont think there much other options and you should understand pretty well, what I mean with Google Push Servers Works on Element, Ntfy doesnt work or very unreliable.
> > I think it should be first priority for a secure and private messenger like element to support ntfy push implemention. I really dont know if the cause is synapse itself or element.
> > the issues are multiple present. All of them dont realy get answered at all, here are my two issues:
> > [element-hq/synapse#17269](https://github.com/element-hq/synapse/issues/17269) #8761
> 
> Google Push isn't a server, it's a service local to your device, which is where the confusion comes from.
> 
> In my case I/we have already been using Google Push Services for actual years and still have problems.
> 
> And yeah it is unclear if it's a synapse/matrix issue or Element issue, but the silence from github issue lack-of-engagement is deafening. They (Element Devs) used to actually work on notification problems but stopped I think well over a year ago. I have no idea why.

No of course Googles FCM isnt just a local server on your device. Theres a server  same like you run your ntfy instance somewhere that Google controlls and has full aware who is in contact with whom when you use it. 

Its absolutly important that the problem with own ntfy instances is going to be fixed asap

**Comment by warioishere** [comment]
i would like everyone to open request and show the importance of this topic to the devs, so maybe they realize. We need a working Push solution beside of googles FCM bullshit

**Comment by BloodyIron** [comment]
> You are so lucky. I am still waiting for messages to decrypt properly. I don't need notifications, I want to see those messages... (`/discardsession`, deleting cache and so on does not work, all sessions are verified)

Not trying to say your issue isn't worth getting fixed, but that's tangibly off-topic there bud. I empathise with your situation, but let's not necessarily fight amongst ourselves to achieve goals we generally agree are worthwhile. Yours and the ones we speak of too. ❤️

I think what really irks me the most is the lack of any engagement from devs on the topic of notification fixes. Years ago the devs were very active responding, even if it was things we didn't want to hear. Now? Silence... and that's really not okay, especially for something as core to any chat app as reliable notifications (or lack thereof).

**Comment by kroeckx** [comment]
I'm using the f-droid version. As far as I know, it does not use the Google Push Services, which meant that element needs to be running to receive notification. Android sometimes stops element from running in the background. I've installed ntfy about a year ago, changed the android settings so ntfy can keep running in the background, and I probably configured element to use it, and think things have worked without issues for me since then.

**Comment by BloodyIron** [comment]
Still having unreliability for me and some of my friends, but not all, for notifications for element android. This doesn't seem to be a priority for being fixed by the devs somehow even though this is _core functionality for a chat/messaging app_. This topic seems to break and get fixed break again multiple times over the years, I truly do not understand why this keeps breaking and why the devs seem to ignore this. It's been over a year since I posted in this thread and still having issues...

**Comment by su-sd** [comment]
@BloodyIron 
Element-android got replaced by ElementX-Android: https://github.com/element-hq/element-x-android/

**Comment by BloodyIron** [comment]
> [@BloodyIron](https://github.com/BloodyIron) Element-android got replaced by ElementX-Android: https://github.com/element-hq/element-x-android/

It's not even a complete solution (last I checked), with missing features, and element-android is still getting updates. Why does that mean that element-android can't have reliable notifications?

**Comment by su-sd** [comment]
The readme says:

> This client is still supported and receives security updates but no new features or usability enhancements are made.

**Comment by BloodyIron** [comment]
> The readme says:
> 
> > This client is still supported and receives security updates but no new features or usability enhancements are made.

Fixing notifications being broken is neither a new feature, nor a usability enhancement. It is fixing a core functionality bug. You know... the first thing this application is meant to do, chat via text and get alerted of that reliably.

**Comment by warioishere** [comment]
> > The readme says:
> > > This client is still supported and receives security updates but no new features or usability enhancements are made.
> 
> Fixing notifications being broken is neither a new feature, nor a usability enhancement. It is fixing a core functionality bug. You know... the first thing this application is meant to do, chat via text and get alerted of that reliably.

forget it pal, they dont care
